services:
  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_PASSWORD='somepass'
      - POSTGRES_USER='admin'
      - POSTGRES_DB='test'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  # server:
  #   # your code here
  #   depends_on:
  #     db:
  #       condition: service_started

volumes:
  db_data: