services:
  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-'somepass'}
      - POSTGRES_USER=${DB_USER:-'admin'}
      - POSTGRES_DB=${DB_NAME:-'test'}
    ports:
      - '${DB_EXT_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  # server:
  #   # your code here
  #   depends_on:
  #     db:
  #       condition: service_started

volumes:
  db_data:
